name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            # Regular SVG with pink dots and a complementary snake color
            dist/github-snake.svg?color_snake=#9C27B0&color_dots=#880E4F,#C2185B,#F06292,#F8BBD0,#FCF0F5
            # Dark mode SVG with github-dark palette, pink dots, and a complementary snake color
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#9C27B0&color_dots=#880E4F,#C2185B,#F06292,#F8BBD0,#FCF0F5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"
